version: "3"
services:
  etcd1:
    image: "bitnami/etcd:3.4"
    container_name: etcd1
    environment:
      - ETCD_NAME=etcd1
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks: [ patroni ]

  etcd2:
    image: "bitnami/etcd:3.4"
    container_name: etcd2
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks: [ patroni ]

  etcd3:
    image: "bitnami/etcd:3.4"
    container_name: etcd3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2379
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      - ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      - ETCD_INITIAL_CLUSTER_STATE=new
    networks: [ patroni ]

  haproxy:
    image: "bitnami/haproxy:2.7.6"
    container_name: haproxy
    ports:
      - "5000:5000"
    volumes:
      - ./haproxy/haproxy.cfg:/bitnami/haproxy/conf/haproxy.cfg
    networks: [ patroni ]
    depends_on: [ patroni1, patroni2, patroni3 ]

  patroni1:
    build: patroni
    container_name: patroni1
    environment:
      PATRONI_NAME: patroni1
    volumes:
      - patroni1:/data/patroni
      - ./patroni/setup.sh:/usr/local/bin/scripts/setup.sh
    networks: [ patroni ]
    depends_on: [ etcd1, etcd2, etcd3 ]

  patroni2:
    build: patroni
    container_name: patroni2
    environment:
      PATRONI_NAME: patroni2
    volumes:
      - patroni2:/data/patroni
      - ./patroni/setup.sh:/usr/local/bin/scripts/setup.sh
    networks: [ patroni ]
    depends_on: [ etcd1, etcd2, etcd3 ]

  patroni3:
    build: patroni
    container_name: patroni3
    environment:
      PATRONI_NAME: patroni3
    volumes:
      - patroni3:/data/patroni
      - ./patroni/setup.sh:/usr/local/bin/scripts/setup.sh
    networks: [ patroni ]
    depends_on: [ etcd1, etcd2, etcd3 ]

networks:
  patroni:

volumes:
  patroni1:
  patroni2:
  patroni3: