spring:
  datasource:
    url: jdbc:postgresql://localhost:5000/testdb
    username: program
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
